language: python

python:
    - "3.5"

sudo: false

env:
    - TOX_ENV=py34-django17
    - TOX_ENV=py33-django17
    - TOX_ENV=py32-django17
    - TOX_ENV=py27-django17
    - TOX_ENV=py35-django18
    - TOX_ENV=py34-django18
    - TOX_ENV=py33-django18
    - TOX_ENV=py32-django18
    - TOX_ENV=py27-django18
    - TOX_ENV=py35-django19
    - TOX_ENV=py34-django19
    - TOX_ENV=py27-django19
    - TOX_ENV=py35-django110
    - TOX_ENV=py34-django110
    - TOX_ENV=py27-django110

matrix:
    fast_finish: true
    allow_failures:
      - env: TOX_ENV=py32-django17
      - env: TOX_ENV=py33-django17
      - env: TOX_ENV=py34-django17
      - env: TOX_ENV=py27-django110
      - env: TOX_ENV=py34-django110
      - env: TOX_ENV=py35-django110

install:
    # Virtualenv < 14 for python 3.2 build
    - pip install tox "virtualenv<14"

script:
    - tox -e $TOX_ENV

notifications:
    email: false
