# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_stats2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelstat',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='modelstat',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='modelstat',
            unique_together=set([('content_type', 'object_id', 'name', 'date')]),
        ),
    ]
